title: Leetcode Fetcher
email: riccardo.lamarca98@gmail.com
description: >-
  Leetcode Fetcher is a CLI Application to interact with leetcode API
  in order to fetch problems locally, test and submit solutions.

domain: "lmriccardo.github.io"
baseurl: "/leetcode-fetcher"
url: "https://lmriccardo.github.io"
github_username: lmriccardo
linkedin_username: riccardolamarca98

# Build settings
theme: minima
plugins:
  - jekyll-feed

header_pages:
  - _pages/about.md
  - _pages/releases.md

exclude:
  - Gemfile
  - Gemfile.lock

collections:
  pages:
    output: true
    permalink: /:path/