title: Leetcode Fetcher
email: riccardo.lamarca98@gmail.com
description: >-
  Leetcode Fetcher is a CLI Application to interact with leetcode API
  in order to fetch problems locally, test and submit solutions.

domain: "lmriccardo.github.io"
baseurl: "/leetcode-fetcher"
url: "https://lmriccardo.github.io"
github_username: lmriccardo
linkedin_username: riccardolamarca98

# Build settings
theme: minima
plugins:
  - jekyll-feed

header_pages:
  - about.md

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
