name: Docker push on Release Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Docker Login
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
      # Setup docker buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Docker build and push on docker hub
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ github.workspace }}/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/leetcode-fetcher:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/leetcode-fetcher:${{ github.ref_name }}
      
      # Verify the pushed image (Optional)
      - name: Verify image
        run: |
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/leetcode-fetcher:latest